test-air:
	/home/mateusz/boolhub/scripts/venv/bin/python /home/mateusz/boolhub/scripts/gatherer.py --data "air"

test-network:
	/home/mateusz/boolhub/scripts/venv/bin/python /home/mateusz/boolhub/scripts/gatherer.py --data "network"
