# Generated by Django 4.1 on 2024-02-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("network", "Urządzenie sieciowe"),
                            ("computer", "PC/Laptop"),
                            ("smartphone", "Smartfon/Komórka"),
                            ("tablet", "Tablet/Czytnik"),
                            ("printer", "Drukarka"),
                            ("tv", "TV/Odtwarzacz multimedialny"),
                            ("light", "Oświetlenie"),
                            ("air", "Oczyszczacz powietrza/termometr"),
                            ("console", "Konsola"),
                            ("other", "Inne"),
                        ],
                        max_length=50,
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=17)),
                ("ip_address", models.CharField(blank=True, max_length=15, null=True)),
                ("token", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
