# Generated by Django 4.1 on 2022-10-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(default='192.168.0.1', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('network', 'Urządzenie sieciowe'), ('computer', 'PC/Laptop'), ('smartphone', 'Smartfon/Komórka'), ('tablet', 'Tablet/Czytnik'), ('printer', 'Drukarka'), ('tv', 'TV/Odtwarzacz multimedialny'), ('light', 'Oświetlenie'), ('air', 'Oczyszczacz/Nawilżacz powietrza'), ('console', 'Konsola')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
