# Generated by Django 4.1 on 2022-10-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_ip_address_alter_device_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('network', 'Urządzenie sieciowe'), ('computer', 'PC/Laptop'), ('smartphone', 'Smartfon/Komórka'), ('tablet', 'Tablet/Czytnik'), ('printer', 'Drukarka'), ('tv', 'TV/Odtwarzacz multimedialny'), ('light', 'Oświetlenie'), ('air', 'Oczyszczacz powietrza/termometr'), ('console', 'Konsola')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
