# Generated by Django 4.1 on 2022-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_category_alter_device_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
